@startuml

header Bing Resy Sequence Diagram
footer Page %page% of %lastpage%
title "Update Reservation (PUT)"

participant "client" as client
participant "<<JavaScript>>\nserver" as server
participant "<<Router>>\nreservations" as reservationsRouter
participant "<<Controller>>\nreservations" as reservationsController
participant "<<Model>>\nreservations" as reservationsModel
database "<<MongoDB>>\nreservations" as reservationsDatabase

client -> server ++: req.put("/api/v1/reservations/:id")
server -> reservationsRouter ++: app.use("/api/v1/reservations",restaurantRouter)
reservationsRouter -> reservationsController ++: updateReservation()
reservationsController -> reservationsModel ++: Reservation.findOneAndUpdate(filterQuery,req.body,{new:true})
reservationsModel -> reservationsDatabase ++:Reservationschema
reservationsDatabase -> reservationsModel --:reservation
reservationsModel -> reservationsController --:reservations
reservationsController -> client --:response

@enduml