@startuml

header Bing Resy Sequence Diagram
footer Page %page% of %lastpage%
title "Get Restaurant (GET)"

participant "client" as client
participant "<<JavaScript>>\nserver" as server
participant "<<Router>>\nrestaurants" as restaurantsRouter
participant "<<Controller>>\nrestaurants" as restaurantsController
participant "<<Model>>\nrestaurants" as restaurantsModel
database "<<MongoDB>>\nrestaurants" as restaurantsDatabase

client -> server ++: req.get("/api/v1/restaurant/:id")
server -> restaurantsRouter ++: app.use("/api/v1/restaurants",restaurantRouter)
restaurantsRouter -> restaurantsController ++: getRestaurant()
alt Have valid login token
    restaurantsController -> restaurantsModel ++: Restaurant.findById(req.params.id).populate(populateQuery)
else Doesn't have valid login token
    restaurantsController -> restaurantsModel --: Restaurant.findById(req.params.id)
end
restaurantsModel -> restaurantsDatabase ++:RestaurantSchema
restaurantsDatabase -> restaurantsModel --:restaurants
restaurantsModel -> restaurantsController --:restaurants
restaurantsController -> client --:response

@enduml